#!/usr/bin/env bash
#
# Copyright 2016 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

command -v img2txt >/dev/null 2>&1 || exit 1
[ -n "$TMDIR" ] || TMPDIR=$(mktemp -d /dev/shm/$PKG.XXXXXXXXX)
trap "rm -rf $TMPDIR; pkill -f -9 lib/wallstreet/ >/dev/null 2>&1; exit" HUP INT QUIT TERM

URL=http://www.wsj.com/news/markets

while [ ! -s $TMPDIR/images ]; do
	wget -q -O- $URL | sed -e "s/\.jpg/.jpg\n/g" | sed -e "s/.*http/http/g" | grep "^http.*\/images\/.*jpg$" | grep -v "\"" >$TMPDIR/images 2>/dev/null
done
while true; do
	clear
	wget -q -O- $(shuf -n1 $TMPDIR/images) >$TMPDIR/image.jpg 2>/dev/null
	img2txt -W $(tput cols) $TMPDIR/image.jpg
	sleep 10
done
rm -rf "$TMPDIR"
