#!/usr/bin/env bash
#
# Copyright 2016 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

command -v jp2a >/dev/null 2>&1 || exit 1
f=$(mktemp)

URL="http://www.wsj.com"
URL="http://www.wsj.com/news/markets"

trap "rm -f $f; pkill -f -9 lib/wallstreet/ >/dev/null 2>&1; exit" HUP INT QUIT TERM
wget -q -O- $URL | sed -e "s/\.jpg/.jpg\n/g" | sed -e "s/.*http/http/g" | grep "^http.*\/images\/.*jpg$" | grep -v "\"" >$f 2>/dev/null
while true; do
	clear
	jp2a -b --color --term-fit $(shuf -n1 $f)
	sleep 3
done
rm -f $f
