#!/usr/bin/env bash
#
# Copyright 2016 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

command -v rsstail >/dev/null 2>&1 || exit 1

URL=http://feeds.reuters.com/news/wealth

trap "pkill -f -9 lib/wallstreet/ >/dev/null 2>&1; exit" HUP INT QUIT TERM
printf '\e[38;5;226m'
#printf '\e[48;5;0m'
while true; do
	pkill -f -9 "rsstail.*28374" 2>/dev/null || true
	rsstail -H -N -d -i 60 -b 28374 -u $URL | grep "Reuters"
	sleep 1
done
