#!/bin/sh
#
# Copyright 2016 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

command -v w3m >/dev/null 2>&1 || exit 1
PKG="wallstreet"

[ -n "$TMDIR" ] || TMPDIR=$(mktemp -d /dev/shm/$PKG.XXXXXXXXX)
trap "rm -rf $TMPDIR; pkill -f -9 lib/wallstreet/ >/dev/null 2>&1; exit" HUP INT QUIT TERM
URL=http://finance.yahoo.com/

while true; do
	w3m -dump "$URL" >$TMPDIR/finance 2>/dev/null
	clear
	cat $TMPDIR/finance | \
		egrep "[0-9]%|^[A-Z]+\s\s+.*[0-9]" | \
		sed -e "s/^\[.*\]\s\+//" | \
		/usr/lib/$PKG/breaks | \
		perl -pe 's:-[0-9\.%]+[^\s\)]:\033[31;1m$&\033[30;0m:g' | \
		perl -pe 's:\+[0-9\.%]+[^\s\)]:\033[32;1m$&\033[30;0m:g' | \
		perl -pe 's:\s[\(\s][0-9\.]+%[\)\s]:\033[32;1m$&\033[30;0m:g' | \
		perl -pe 's:^.+\s\s:\033[34;1m$&\033[30;0m:' | \
		perl -pe 's:[0-9.,]+[\sMB]:\033[35;1m$&\033[30;0m:g'
	sleep 60
done
rm -rf "$TMPDIR"
