#!/bin/sh
#
# Copyright 2014 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

declare -g PID=0
declare -g CHANGE=0

# Minimum terminal size required for `bmon --show-all`
MIN_ROWS=11
MIN_COLS=48

check_win_size(){
    if [ $(tput lines) -lt $MIN_ROWS ] || [ $(tput cols) -lt $MIN_COLS ];then
        CHANGE=1
    fi
}

check_win_size
if [ $CHANGE -eq 1 ];then
    exec ./speedometer
fi

command -v bmon >/dev/null 2>&1 || exit 1

trap "check_win_size" WINCH
trap "pkill -f -9 lib/hollywood/ >/dev/null 2>&1; exit" INT
trap "kill -9 $PID" EXIT

bmon --show-all &
PID=$!

# Prevent WINCH signal interruption of the `wait` command
while [ $CHANGE -ne 1 ];do
    wait $PID
done
kill $PID
exec ./speedometer