#!/usr/bin/env bash
#
# Copyright 2014-2023 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# locate would be faster, but find is more universal
command -v find >/dev/null 2>&1 || exit 1
# try to colorize our code, but if not, just print it to screen
command -v pygmentize >/dev/null 2>&1 && viewer="pygmentize" || viewer="cat"

trap "pkill -f -9 lib/hollywood/ >/dev/null 2>&1; exit" INT
while true; do
	FILES=$(find /usr -readable -size +0 -type f -name \*.java -o -name \*.c -o -name \*.cpp -o -name \*.py 2>/dev/null | sort -R)
	for f in $FILES; do
		$viewer "$f" 2>/dev/null || true
		sleep 2
	done
done
