#!/bin/bash
#
# Copyright 2014 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

command -v locate >/dev/null 2>&1 || exit 1
command -v jp2a >/dev/null 2>&1 || exit 1

trap "pkill -f -9 lib/hollywood/ >/dev/null 2>&1" HUP INT QUIT TERM
while true; do
	FILES=$(locate "/usr/*jpg" | sort -R | head -n 4096)
	for f in $FILES; do
		[ -r "$f" ] || continue
		[ -s "$f" ] || continue
		[ -f "$f" ] || continue
		clear
		jp2a --colors --term-fit "$f"
		sleep 0.57
	done
done
