#!/usr/bin/env sh
#
# Copyright 2026 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

command -v mtr >/dev/null 2>&1 || exit 1

trap "pkill -f -9 lib/hollywood/ >/dev/null 2>&1; exit" INT
while true; do
	target=$(printf "8.8.8.8\n1.1.1.1\n9.9.9.9\n208.67.222.222\n4.2.2.1\n198.41.0.4\n199.7.83.42\n192.5.5.241" | sort -R | head -n1)
	mtr --report-wide --report-cycles 3 "$target" 2>/dev/null
	sleep 2
done
