#!/bin/sh
#
# Copyright 2014 Dustin Kirkland <dustin.kirkland@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

command -v ssh-keygen >/dev/null 2>&1 || exit 1
command -v ccze >/dev/null 2>&1 || exit 1

tmpdir=$(mktemp -d -t XXXXXX)
trap "rm -rf $tmpdir 2>/dev/null && pkill -f -9 lib/hollywood/ >/dev/null 2>&1" HUP INT QUIT TERM

while true; do
	sleep 3 &
	tmpfile=$(mktemp -p "$tmpdir" -t XXXXXX)
	rm -f $tmpfile
	art=$(ssh-keygen -vvv -b 1024 -t dsa -N "" -f $tmpfile)
	rm -f $tmpfile $tmpfile.pub
	wait
	clear
	echo "$art" | ccze -A -c default=red
done
