#!/bin/sh

tmpfile=$(mktemp)
trap "exec rm -f $tmpfile $tmpfile.pub 2>/dev/null" EXIT HUP INT QUIT TERM

while true; do
	rm -f $tmpfile $tmpfile.pub
	ssh-keygen -vvv -b 1024 -t dsa -N "" -f $tmpfile | ccze -A -c default=red
	sleep 3
	clear
done
