.TH hollywood 1 "15 December 2014" hollywood "hollywood"
.SH NAME
hollywood \- fill your console with Holly melodrama technobabble

.SH SYNOPSIS
\fBhollywood\fP [SPLITS]

.SH OPTIONS

    SPLITS	The number of splits to divide your screen

.SH DESCRIPTION

This utility will fill your console with Hollywood melodrama technobabble.

It will split your \fBbyobu\fP(1) console into a multiple panes of genuine technobabble, perfectly suitable for any Hollywood geek melodrama.

It is particularly suitable on any number of computer consoles in the background of any excellent schlock technothriller.

To quit, press Ctrl-C to kill the \fBhollywood\fP script itself.

While \fBhollywood\fP tries not to overwhelm your system by running widgets with the minimum scheduling priority per \fBnice\fP(1)

.SH SEE ALSO
\fBbyobu\fP(1), \fBnice\fP(1)

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <dustin.kirkland@gmail.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the Apache2 License.

The complete text of the Apache2 License can be found in \fI/usr/share/common-licenses/Apache-2.0\fP on Debian/Ubuntu systems.
