.TH wallstreet 1 "24 January 2017" wallstreet "wallstreet"
.SH NAME
wallstreet \- fill your console with wallstreet melodrama technobabble

.SH SYNOPSIS
\fBwallstreet\fP [SPLITS]

.SH OPTIONS

    SPLITS  The number of splits to divide your screen

.SH DESCRIPTION

This utility will fill your console with Wall Street technobabble.

It will split your \fBbyobu\fP(1) console into a multiple panes of news and statistics, like any good computer screen on Wall Street.

To quit, press Ctrl-C to kill the \fBwallstreet\fP script itself.

.SH SEE ALSO
\fBbyobu\fP(1), \fBnice\fP(1)

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <dustin.kirkland@gmail.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the Apache2 License.

The complete text of the Apache2 License can be found in \fI/usr/share/common-licenses/Apache-2.0\fP on Debian/Ubuntu systems.
