[DEFAULT]
upstream-branch = upstream
debian-branch = master
pristine-tar = False

[buildpackage]
upstream-tree = HEAD
filter = ['debian', '.maintainer']
filter-pristine-tar = False
sign-tags = False

[export-orig]
upstream-tree = HEAD
filter = ['debian', '.maintainer']
filter-pristine-tar = False
